CREATE TABLE permissions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL
);

CREATE TABLE user_permissions (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE groups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE user_groups (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE file_nodes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kind TEXT NOT NULL CHECK (kind IN ('file', 'folder', 'alias')),
    name TEXT NOT NULL CHECK (name <> '' AND POSITION('/' IN name) = 0),
    parent_id INTEGER REFERENCES file_nodes(id) ON DELETE CASCADE,
    alias_target_id INTEGER REFERENCES file_nodes(id) ON DELETE RESTRICT,
    object_key TEXT,
    size BIGINT,
    comment TEXT,
    is_dropbox BOOLEAN NOT NULL DEFAULT FALSE,
    creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (parent_id IS NULL OR parent_id <> id),
    CHECK (alias_target_id IS NULL OR alias_target_id <> id),
    CHECK (
        (kind = 'file'
         AND object_key IS NOT NULL
         AND alias_target_id IS NULL
         AND size IS NOT NULL
         AND size >= 0
         AND is_dropbox = FALSE)
        OR
        (kind = 'folder'
         AND object_key IS NULL
         AND alias_target_id IS NULL
         AND size IS NULL)
        OR
        (kind = 'alias'
         AND object_key IS NULL
         AND alias_target_id IS NOT NULL
         AND size IS NULL
         AND is_dropbox = FALSE)
    )
);

CREATE UNIQUE INDEX idx_file_nodes_root_name
    ON file_nodes(name)
    WHERE parent_id IS NULL;

CREATE UNIQUE INDEX idx_file_nodes_child_name
    ON file_nodes(parent_id, name)
    WHERE parent_id IS NOT NULL;

CREATE UNIQUE INDEX idx_file_nodes_object_key
    ON file_nodes(object_key)
    WHERE object_key IS NOT NULL;

CREATE INDEX idx_file_nodes_parent_name
    ON file_nodes(parent_id, name);

CREATE INDEX idx_file_nodes_alias_target
    ON file_nodes(alias_target_id);

CREATE INDEX idx_file_nodes_creator
    ON file_nodes(creator_id);

CREATE TABLE resource_permissions (
    resource_type TEXT NOT NULL CHECK (resource_type = 'file_node'),
    resource_id INTEGER NOT NULL REFERENCES file_nodes(id) ON DELETE CASCADE,
    principal_type TEXT NOT NULL CHECK (principal_type IN ('user', 'group')),
    principal_id INTEGER NOT NULL,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (
        resource_type,
        resource_id,
        principal_type,
        principal_id,
        permission_id
    )
);

CREATE INDEX idx_resource_permissions_lookup
    ON resource_permissions(
        resource_type,
        principal_type,
        principal_id,
        permission_id,
        resource_id
    );

CREATE INDEX idx_resource_permissions_resource
    ON resource_permissions(resource_type, resource_id);

CREATE OR REPLACE FUNCTION validate_resource_permission_principal()
RETURNS trigger AS $$
BEGIN
    IF NEW.principal_type = 'user' THEN
        IF NOT EXISTS (SELECT 1 FROM users WHERE id = NEW.principal_id) THEN
            RAISE EXCEPTION
                'resource_permissions principal % is not a valid user',
                NEW.principal_id;
        END IF;
    ELSIF NEW.principal_type = 'group' THEN
        IF NOT EXISTS (SELECT 1 FROM groups WHERE id = NEW.principal_id) THEN
            RAISE EXCEPTION
                'resource_permissions principal % is not a valid group',
                NEW.principal_id;
        END IF;
    ELSE
        RAISE EXCEPTION
            'resource_permissions principal type % is invalid',
            NEW.principal_type;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER validate_resource_permissions_principal
    BEFORE INSERT OR UPDATE ON resource_permissions
    FOR EACH ROW
    EXECUTE FUNCTION validate_resource_permission_principal();

CREATE OR REPLACE FUNCTION delete_user_resource_permissions()
RETURNS trigger AS $$
BEGIN
    DELETE FROM resource_permissions
    WHERE principal_type = 'user'
      AND principal_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER cleanup_user_resource_permissions
    AFTER DELETE ON users
    FOR EACH ROW
    EXECUTE FUNCTION delete_user_resource_permissions();

CREATE OR REPLACE FUNCTION delete_group_resource_permissions()
RETURNS trigger AS $$
BEGIN
    DELETE FROM resource_permissions
    WHERE principal_type = 'group'
      AND principal_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER cleanup_group_resource_permissions
    AFTER DELETE ON groups
    FOR EACH ROW
    EXECUTE FUNCTION delete_group_resource_permissions();
