//! Diesel schema definitions.
//!
//! Generated by `diesel print-schema`. These definitions describe the layout of
//! tables used by the application.
// FIXME: https://github.com/diesel-rs/diesel/issues/3534 - diesel macros don't support doc attrs
#![expect(missing_docs, reason = "diesel macros generate undocumented items")]

diesel::table! {
    users (id) {
        id -> Integer,
        username -> Text,
        password -> Text,
    }
}
diesel::table! {
    news_bundles (id) {
        id -> Integer,
        parent_bundle_id -> Nullable<Integer>,
        name -> Text,
        guid -> Nullable<Text>,
        created_at -> Nullable<Timestamp>,
    }
}
diesel::table! {
    news_categories (id) {
        id -> Integer,
        bundle_id -> Nullable<Integer>,
        name -> Text,
        guid -> Nullable<Text>,
        add_sn -> Nullable<Integer>,
        delete_sn -> Nullable<Integer>,
        created_at -> Nullable<Timestamp>,
    }
}
diesel::table! {
    files (id) {
        id -> Integer,
        name -> Text,
        object_key -> Text,
        size -> BigInt,
    }
}

diesel::table! {
    news_articles (id) {
        id -> Integer,
        category_id -> Integer,
        parent_article_id -> Nullable<Integer>,
        prev_article_id -> Nullable<Integer>,
        next_article_id -> Nullable<Integer>,
        first_child_article_id -> Nullable<Integer>,
        title -> Text,
        poster -> Nullable<Text>,
        posted_at -> Timestamp,
        flags -> Integer,
        data_flavor -> Nullable<Text>,
        data -> Nullable<Text>,
    }
}

diesel::table! {
    file_acl (file_id, user_id) {
        file_id -> Integer,
        user_id -> Integer,
    }
}

diesel::table! {
    permissions (id) {
        id -> Integer,
        code -> Integer,
        name -> Text,
        scope -> Text,
    }
}

diesel::table! {
    user_permissions (user_id, permission_id) {
        user_id -> Integer,
        permission_id -> Integer,
    }
}

diesel::joinable!(file_acl -> files (file_id));
diesel::joinable!(file_acl -> users (user_id));
diesel::joinable!(news_articles -> news_categories (category_id));
diesel::joinable!(news_categories -> news_bundles (bundle_id));
diesel::joinable!(user_permissions -> permissions (permission_id));
diesel::joinable!(user_permissions -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    file_acl,
    files,
    news_articles,
    news_bundles,
    news_categories,
    permissions,
    user_permissions,
    users,
);
