//! Diesel schema definitions.
//!
//! Generated by `diesel print-schema`. These definitions describe the layout of
//! tables used by the application.

#![allow(missing_docs, reason = "diesel macros generate undocumented items")]

diesel::table! {
    users (id) {
        id -> Integer,
        username -> Text,
        password -> Text,
    }
}
diesel::table! {
    news_bundles (id) {
        id -> Integer,
        parent_bundle_id -> Nullable<Integer>,
        name -> Text,
    }
}
diesel::table! {
    news_categories (id) {
        id -> Integer,
        name -> Text,
        bundle_id -> Nullable<Integer>,
    }
}
diesel::table! {
    files (id) {
        id -> Integer,
        name -> Text,
        object_key -> Text,
        size -> BigInt,
    }
}

diesel::table! {
    news_articles (id) {
        id -> Integer,
        category_id -> Integer,
        parent_article_id -> Nullable<Integer>,
        prev_article_id -> Nullable<Integer>,
        next_article_id -> Nullable<Integer>,
        first_child_article_id -> Nullable<Integer>,
        title -> Text,
        poster -> Nullable<Text>,
        posted_at -> Timestamp,
        flags -> Integer,
        data_flavor -> Nullable<Text>,
        data -> Nullable<Text>,
    }
}

diesel::table! {
    file_acl (file_id, user_id) {
        file_id -> Integer,
        user_id -> Integer,
    }
}

diesel::allow_tables_to_appear_in_same_query!(files, file_acl);
